[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --noinput && daphne -b 0.0.0.0 -p $PORT config.asgi:application"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
