[deploy]
startCommand = "daphne -b 0.0.0.0 -p $PORT config.asgi:application"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build]
builder = "nixpacks"

[[build.buildCommand]]
cmd = "python manage.py collectstatic --noinput"

[[build.buildCommand]]
cmd = "python manage.py migrate"

[[build.buildCommand]]
cmd = "python manage.py seed_media_outlets"

[[build.buildCommand]]
cmd = "python manage.py load_budget_phrases"
